# This file contains the information needed for Shopify to authenticate
# requests and edit/update your remote theme files.
#
# 1. In the Shopify Store's Admin panel, click the "Apps" link on the left, then in the bottom of the page select "Manage Private Apps". From there, open or create a new token called "BOL-Development" and copy its Password key.
# 2. Replace the required variables for each environment below into a new file and save it with the name "config.yml" in the project root.
#
# NOTE : password, theme_id, and store variables are required!
#
# For more information on this config file:
#   Configuration variables | http://shopify.github.io/themekit/configuration/
#   Ignore patterns | http://shopify.github.io/themekit/ignores/



development:
  password: fa50737aef124ed48d6de3cd8c72f0d6 
  theme_id: "79443722343" #Needs the quotes around the ID value
  store: brookstone-prod.myshopify.com
  ignore_files:
    - assets/theme.js.map
    - README.md
    - .gitignore
    - settings_data.json
    - theme.lock
    - locales/
    - "*.png"
    - "*.jpg"  
    - "*.jpeg" 
    - "*.svg" 
    - "*.gif" 


